# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # setting up python
      - name: setup python
        uses: actions/setup-python@v2
        with:
            python-version: 3.9.6
                 
      # setting up pip and added requiments.txt
      - name: install pip and requirements.txt
        run: |
            python -m pip install --upgrade pip
            
      
      
  get-jira-features-build:
    # The type of runner that the job will run on
    needs: [build]
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
      # run python files
      - name: get features from jira
        run: |
            python -m venv virtualenv
            cd virtualenv/Scripts
            ls
            .\activate
            cd ../..
            pip install -r requirements.txt
            python triggerfeaturesfromjira.py tickets.ini
            
      
      - name: get test results output in cucumber json
        run: |
            ls
            cd virtualenv/Scripts
            .\activate
            cd ../..
            pytest -v -s features\test_dem.py --cucumberjson=results/outputs.json
          
  
  import-to-jira-build:
    # The type of runner that the job will run on
    needs: [get-jira-features-build]
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: upload execution results to jira
        run: |
             cd virtualenv/Scripts
             .\activate
             cd ../..
             python importtojira.py
        
